var annotated_dup =
[
    [ "can_eps_status_t", "structcan__eps__status__t.html", "structcan__eps__status__t" ],
    [ "can_frame_t", "structcan__frame__t.html", "structcan__frame__t" ],
    [ "can_heartbeat_t", "structcan__heartbeat__t.html", "structcan__heartbeat__t" ],
    [ "can_instr_accel_t", "structcan__instr__accel__t.html", "structcan__instr__accel__t" ],
    [ "can_instr_altitude_t", "structcan__instr__altitude__t.html", "structcan__instr__altitude__t" ],
    [ "can_instr_gas_t", "structcan__instr__gas__t.html", "structcan__instr__gas__t" ],
    [ "can_instr_housekeeping_t", "structcan__instr__housekeeping__t.html", "structcan__instr__housekeeping__t" ],
    [ "can_instr_humidity_t", "structcan__instr__humidity__t.html", "structcan__instr__humidity__t" ],
    [ "can_instr_pressure_t", "structcan__instr__pressure__t.html", "structcan__instr__pressure__t" ],
    [ "can_instr_status_t", "structcan__instr__status__t.html", "structcan__instr__status__t" ],
    [ "can_master_status_t", "structcan__master__status__t.html", "structcan__master__status__t" ],
    [ "can_photonics_adc_t", "structcan__photonics__adc__t.html", "structcan__photonics__adc__t" ],
    [ "can_photonics_uv_t", "structcan__photonics__uv__t.html", "structcan__photonics__uv__t" ],
    [ "eps_comms_t", "structeps__comms__t.html", "structeps__comms__t" ],
    [ "eps_control_t", "structeps__control__t.html", "structeps__control__t" ],
    [ "eps_data_t", "structeps__data__t.html", "structeps__data__t" ],
    [ "eps_raw_t", "structeps__raw__t.html", "structeps__raw__t" ],
    [ "hal_adc_t", "structhal__adc__t.html", "structhal__adc__t" ],
    [ "hal_ads1115_t", "structhal__ads1115__t.html", "structhal__ads1115__t" ],
    [ "hal_imu_t", "structhal__imu__t.html", "structhal__imu__t" ],
    [ "hal_ms5611_t", "structhal__ms5611__t.html", "structhal__ms5611__t" ],
    [ "hal_scd41_t", "structhal__scd41__t.html", "structhal__scd41__t" ],
    [ "hal_sht45_t", "structhal__sht45__t.html", "structhal__sht45__t" ],
    [ "hal_uv_t", "structhal__uv__t.html", "structhal__uv__t" ],
    [ "instr_comms_t", "structinstr__comms__t.html", "structinstr__comms__t" ],
    [ "master_comms_t", "structmaster__comms__t.html", "structmaster__comms__t" ],
    [ "master_flight_t", "structmaster__flight__t.html", "structmaster__flight__t" ],
    [ "photonics_comms_t", "structphotonics__comms__t.html", "structphotonics__comms__t" ],
    [ "sys_cmd_def_t", "structsys__cmd__def__t.html", "structsys__cmd__def__t" ],
    [ "util_bangbang_t", "structutil__bangbang__t.html", "structutil__bangbang__t" ],
    [ "util_ema_t", "structutil__ema__t.html", "structutil__ema__t" ],
    [ "util_ntc_cfg_t", "structutil__ntc__cfg__t.html", "structutil__ntc__cfg__t" ]
];